### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by lukhio** [Fare9/KUNAI-static-analyzer#46]
I run into this error when compiling with `./make.sh build` on Ubuntu 22.04.1 LTS. This is using `g++` version 11.2.0. The error message is very long, but basically I get the same kind of error all the time, some undefined references when linking:

```
/usr/bin/ld: objs/test_ir.o: in function `spdlog::details::aggregate_formatter::format(spdlog::details::log_msg const&, tm const&, fmt::v8::basic_memory_buffer<char, 250ul, std::allocator<char> >&)':
test_ir.cpp:(.text._ZN6spdlog7details19aggregate_formatter6formatERKNS0_7log_msgERK2tmRN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE[_ZN6spdlog7details19aggregate_formatter6formatERKNS0_7log_msgERK2tmRN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE]+0xc3): undefined reference to `fmt::v8::detail::assert_fail(char const*, int, char const*)'
```
From various StackOverflow posts it might be due to includes being in the wrong order thus creating undefined references, but I'm not familiar enough with KUNAI's code to check if that is the case here.

Here is the full error message for reference: https://pastebin.com/mK5pCX9r

Happy to do more tests if needed!

**Comment by Fare9** [comment]
I worked on modifying the `make.sh` script, you can try the one from dev branch, this one will install spdlog from source, probably fixing the issue: https://github.com/Fare9/KUNAI-static-analyzer/blob/dev/debian_distros_installer.sh
Thanks!

**Comment by lukhio** [comment]
Hmm I still get the same error with that branch, although there seems to be much less occurences:
```
Linking objs/main.o -> bin/Kunai
/usr/bin/ld: objs/main.o: in function `void fmt::v8::detail::buffer<char>::append<char>(char const*, char const*) [clone .constprop.0]':
main.cpp:(.text+0xcfe): undefined reference to `fmt::v8::detail::assert_fail(char const*, int, char const*)'
/usr/bin/ld: objs/main.o: in function `spdlog::pattern_formatter::format(spdlog::details::log_msg const&, fmt::v8::basic_memory_buffer<char, 250ul, std::allocator<char> >&)':
main.cpp:(.text._ZN6spdlog17pattern_formatter6formatERKNS_7details7log_msgERN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE[_ZN6spdlog17pattern_formatter6formatERKNS_7details7log_msgERN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE]+0x1cb): undefined reference to `fmt::v8::detail::assert_fail(char const*, int, char const*)'
/usr/bin/ld: objs/main.o: in function `fmt::v8::detail::for_each_codepoint<fmt::v8::detail::compute_width(fmt::v8::basic_string_view<char>)::count_code_points>(fmt::v8::basic_string_view<char>, fmt::v8::detail::compute_width(fmt::v8::basic_string_view<char>)::count_code_points)::{lambda(char const*, char const*)#1}::operator()(char const*, char const*) const':
main.cpp:(.text._ZZN3fmt2v86detail18for_each_codepointIZNS1_13compute_widthENS0_17basic_string_viewIcEEE17count_code_pointsEEvS4_T_ENKUlPKcS8_E_clES8_S8_[_ZZN3fmt2v86detail18for_each_codepointIZNS1_13compute_widthENS0_17basic_string_viewIcEEE17count_code_pointsEEvS4_T_ENKUlPKcS8_E_clES8_S8_]+0x266): undefined reference to `fmt::v8::detail::assert_fail(char const*, int, char const*)'
```

**Comment by Fare9** [comment]
Is it the correct version of `spdlog`? I know there are some issues using newer versions from this library, for that reason the installer downloads version `1.5.0`

**Comment by lukhio** [comment]
I was using the wrong version indeed! So now the installer compiled it from source directly, but then the compilation fails because it is not correctly included:
```
Compiling src/main.cpp -> objs/main.o
Compiling src/Utils/utils.cpp -> objs/utils.o
Compiling src/DEX/parser/dex_header.cpp -> objs/dex_header.o
Compiling src/DEX/parser/dex_strings.cpp -> objs/dex_strings.o
In file included from src/Utils/utils.cpp:1:
src/include/KUNAI/Utils/utils.hpp:5:10: fatal error: spdlog/spdlog.h: No such file or directory
    5 | #include <spdlog/spdlog.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/include/KUNAI/DEX/parser/dex_header.hpp:46,
                 from src/DEX/parser/dex_header.cpp:1:
src/include/KUNAI/Utils/utils.hpp:5:10: fatal error: spdlog/spdlog.h: No such file or directory
    5 | #include <spdlog/spdlog.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/include/KUNAI/DEX/parser/dex_header.hpp:46,
                 from src/include/KUNAI/DEX/parser/dex_parser.hpp:20,
                 from src/include/KUNAI/DEX/dex.hpp:19,
                 from src/main.cpp:7:
src/include/KUNAI/Utils/utils.hpp:5:10: fatal error: spdlog/spdlog.h: No such file or directory
    5 | #include <spdlog/spdlog.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/include/KUNAI/DEX/parser/dex_strings.hpp:36,
                 from src/DEX/parser/dex_strings.cpp:1:
src/include/KUNAI/Utils/utils.hpp:5:10: fatal error: spdlog/spdlog.h: No such file or directory
    5 | #include <spdlog/spdlog.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:145: objs/main.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:215: objs/utils.o] Error 1
make: *** [Makefile:228: objs/dex_header.o] Error 1
make: *** [Makefile:228: objs/dex_strings.o] Error 1
[-] An error ocurred, check output...
```

**Comment by Fare9** [comment]
I'm working now on https://github.com/Fare9/KUNAI-static-analyzer/tree/dev branch, I will merge it right now into main one with the CMake stuff, CMake directly download, compiles and link everything directly into the binaries. I need to setup the installation process yet, but I think is good enough for merging.

**Comment by Fare9** [comment]
Whenever you can update your main branch, I've just merged from dev, as you can see here, both compilations work: https://github.com/Fare9/KUNAI-static-analyzer/actions/runs/3214567932

**Comment by Fare9** [comment]
I think with CMake it shouldn't give any problem, just run in the root folder of Kunai:

```
cmake --B build -S .
cmake --build build -j<number_of_processes>
```

**Comment by lukhio** [comment]
Alright so the `debian_distros_installer.sh` still does not work for me. It does in the CI because there it manages to install the right version of `libspdlog-dev` from the APT repos, but on my system it is not available.

However I can build without problem with `cmake` so I think we can close this issue :)

**Comment by Fare9** [comment]
Just did a last merge, you can find changes in this commit: https://github.com/Fare9/KUNAI-static-analyzer/commit/ff318efb4faf3360419898d878be6c99a637919c. Mostly what I've done is cleaning a little bit the `CMakeLists.txt`, and added the installation, so now you can do the next to compile and install:

```
cmake --B build -S .
cmake --build build -j<number_of_processes>
sudo cmake --build build --target install
```

And later for uninstalling if necessary:

```
sudo cmake --build build --target uninstall
```

With this we can close finally the issue =)
